-- 340 recipes of 17 cuisines, without their embedding: the app computes it at its start
INSERT INTO recipe (name, cuisine, course, vegetarian, minutes, description, created_at, updated_at) VALUES
    -- italian
    ('Spaghetti carbonara', 'italian', 'main', false, 20, 'Spaghetti tossed with egg yolks, pecorino, black pepper and crispy guanciale, creamy without any cream.', NOW(), NOW()),
    ('Margherita pizza', 'italian', 'main', true, 90, 'Thin Neapolitan crust baked very hot with tomato sauce, fresh mozzarella and basil leaves.', NOW(), NOW()),
    ('Risotto alla milanese', 'italian', 'main', true, 40, 'Creamy arborio rice slowly cooked in broth with saffron, butter and parmesan.', NOW(), NOW()),
    ('Lasagne alla bolognese', 'italian', 'main', false, 180, 'Layers of fresh pasta, slow cooked beef and pork ragu, bechamel and parmesan, baked until bubbling.', NOW(), NOW()),
    ('Osso buco', 'italian', 'main', false, 150, 'Veal shanks braised in white wine, tomato and broth until the meat falls off the bone, topped with gremolata.', NOW(), NOW()),
    ('Pasta e fagioli', 'italian', 'soup', true, 60, 'A thick and comforting peasant soup of small pasta, borlotti beans, tomato and rosemary.', NOW(), NOW()),
    ('Minestrone', 'italian', 'soup', true, 50, 'Vegetable soup with zucchini, carrots, beans, cabbage and small pasta, finished with olive oil and parmesan.', NOW(), NOW()),
    ('Bruschetta al pomodoro', 'italian', 'starter', true, 15, 'Grilled bread rubbed with garlic and topped with diced ripe tomatoes, basil and olive oil.', NOW(), NOW()),
    ('Caprese salad', 'italian', 'starter', true, 10, 'Slices of buffalo mozzarella and summer tomatoes with basil, olive oil and flaky salt.', NOW(), NOW()),
    ('Vitello tonnato', 'italian', 'starter', false, 90, 'Cold slices of poached veal covered with a creamy tuna, anchovy and caper sauce.', NOW(), NOW()),
    ('Tiramisu', 'italian', 'dessert', true, 30, 'Ladyfingers soaked in espresso layered with mascarpone cream and dusted with cocoa, chilled overnight.', NOW(), NOW()),
    ('Panna cotta', 'italian', 'dessert', true, 20, 'Silky set vanilla cream served cold with a red berry coulis.', NOW(), NOW()),
    ('Cannoli siciliani', 'italian', 'dessert', true, 60, 'Crisp fried pastry tubes filled with sweet ricotta, candied orange and chocolate chips.', NOW(), NOW()),
    ('Focaccia genovese', 'italian', 'side', true, 180, 'Soft and airy flatbread dimpled with olive oil, coarse salt and rosemary.', NOW(), NOW()),
    ('Penne arrabbiata', 'italian', 'main', true, 20, 'Penne in a fiery tomato sauce with garlic and dried red chili.', NOW(), NOW()),
    ('Spaghetti alle vongole', 'italian', 'main', false, 25, 'Spaghetti with fresh clams, garlic, white wine, parsley and a pinch of chili.', NOW(), NOW()),
    ('Gnocchi al pesto', 'italian', 'main', true, 45, 'Soft potato dumplings with a basil, pine nut and parmesan pesto.', NOW(), NOW()),
    ('Saltimbocca alla romana', 'italian', 'main', false, 20, 'Thin veal escalopes with prosciutto and sage, pan fried and glazed with white wine.', NOW(), NOW()),
    ('Affogato', 'italian', 'dessert', true, 5, 'A scoop of vanilla gelato drowned in a shot of hot espresso.', NOW(), NOW()),
    ('Arancini', 'italian', 'starter', true, 60, 'Fried balls of saffron risotto stuffed with peas and melting mozzarella.', NOW(), NOW()),
    -- french
    ('Boeuf bourguignon', 'french', 'main', false, 210, 'Beef slowly braised in red Burgundy wine with bacon, mushrooms and pearl onions, perfect on a cold winter night.', NOW(), NOW()),
    ('Coq au vin', 'french', 'main', false, 150, 'Chicken stewed in red wine with lardons, mushrooms, garlic and thyme.', NOW(), NOW()),
    ('Ratatouille', 'french', 'main', true, 75, 'A Provencal stew of eggplant, zucchini, peppers, tomatoes and herbs slowly cooked in olive oil.', NOW(), NOW()),
    ('French onion soup', 'french', 'soup', true, 90, 'Deeply caramelized onions in broth, topped with toasted bread and melted gruyere, gratinated under the grill.', NOW(), NOW()),
    ('Quiche lorraine', 'french', 'main', false, 70, 'Buttery shortcrust tart filled with eggs, cream and smoked bacon.', NOW(), NOW()),
    ('Croque monsieur', 'french', 'main', false, 20, 'Toasted ham and cheese sandwich covered with bechamel and grilled until golden.', NOW(), NOW()),
    ('Bouillabaisse', 'french', 'soup', false, 120, 'Marseille fish stew with rockfish, saffron, fennel and orange zest, served with rouille and croutons.', NOW(), NOW()),
    ('Cassoulet', 'french', 'main', false, 240, 'Hearty bake of white beans, duck confit, Toulouse sausage and pork from the southwest of France.', NOW(), NOW()),
    ('Gratin dauphinois', 'french', 'side', true, 90, 'Thinly sliced potatoes baked slowly in cream, milk and garlic until tender and golden.', NOW(), NOW()),
    ('Salade nicoise', 'french', 'starter', false, 25, 'Salad of tuna, boiled eggs, green beans, potatoes, olives, tomatoes and anchovies.', NOW(), NOW()),
    ('Creme brulee', 'french', 'dessert', true, 60, 'Rich vanilla custard under a thin crackling layer of caramelized sugar.', NOW(), NOW()),
    ('Tarte tatin', 'french', 'dessert', true, 75, 'Upside down tart of apples caramelized in butter and sugar, served warm with creme fraiche.', NOW(), NOW()),
    ('Chocolate mousse', 'french', 'dessert', true, 20, 'Airy dark chocolate mousse made with whipped egg whites, chilled for a few hours.', NOW(), NOW()),
    ('Crepes suzette', 'french', 'dessert', true, 40, 'Thin crepes in a buttery orange caramel sauce, flambeed with Grand Marnier.', NOW(), NOW()),
    ('Moules marinieres', 'french', 'main', false, 25, 'Mussels steamed in white wine with shallots, garlic, butter and parsley, served with fries.', NOW(), NOW()),
    ('Blanquette de veau', 'french', 'main', false, 150, 'Veal stewed in a white creamy sauce with mushrooms and carrots, served with rice.', NOW(), NOW()),
    ('Pissaladiere', 'french', 'starter', false, 90, 'Nice onion tart with slowly cooked onions, anchovies and black olives on bread dough.', NOW(), NOW()),
    ('Vichyssoise', 'french', 'soup', true, 45, 'Velvety leek and potato soup with cream, served chilled in summer.', NOW(), NOW()),
    ('Madeleines', 'french', 'dessert', true, 30, 'Small shell shaped butter cakes with a hint of lemon, best warm with tea.', NOW(), NOW()),
    ('Croissants', 'french', 'breakfast', true, 600, 'Flaky laminated pastry with many buttery layers, a weekend breakfast project.', NOW(), NOW()),
    -- japanese
    ('Tonkotsu ramen', 'japanese', 'soup', false, 720, 'Rich and milky pork bone broth with wheat noodles, chashu pork, soft egg and scallions.', NOW(), NOW()),
    ('Miso soup', 'japanese', 'soup', true, 15, 'Light dashi broth with miso paste, tofu cubes, wakame seaweed and green onion.', NOW(), NOW()),
    ('Salmon nigiri', 'japanese', 'main', false, 60, 'Hand pressed vinegared sushi rice topped with slices of raw salmon.', NOW(), NOW()),
    ('Chicken teriyaki', 'japanese', 'main', false, 25, 'Chicken thighs pan fried and glazed with a sweet soy, mirin and sake sauce.', NOW(), NOW()),
    ('Tonkatsu', 'japanese', 'main', false, 30, 'Breaded deep fried pork cutlet with shredded cabbage and a tangy brown sauce.', NOW(), NOW()),
    ('Okonomiyaki', 'japanese', 'main', false, 35, 'Savory cabbage pancake with pork belly, topped with mayonnaise, okonomi sauce and bonito flakes.', NOW(), NOW()),
    ('Vegetable tempura', 'japanese', 'starter', true, 30, 'Sweet potato, eggplant and mushrooms in a light crispy batter, dipped in tentsuyu sauce.', NOW(), NOW()),
    ('Gyoza', 'japanese', 'starter', false, 50, 'Pan fried dumplings filled with pork, cabbage, garlic and ginger, crispy on the bottom.', NOW(), NOW()),
    ('Japanese curry', 'japanese', 'main', false, 60, 'Thick mild and slightly sweet curry with beef, potatoes and carrots over rice.', NOW(), NOW()),
    ('Oyakodon', 'japanese', 'main', false, 20, 'Rice bowl topped with chicken and egg simmered in dashi, soy and mirin.', NOW(), NOW()),
    ('Onigiri', 'japanese', 'side', true, 20, 'Rice balls wrapped in nori and filled with pickled plum, a perfect picnic snack.', NOW(), NOW()),
    ('Agedashi tofu', 'japanese', 'starter', true, 20, 'Lightly fried silken tofu in a warm dashi broth with grated daikon.', NOW(), NOW()),
    ('Yakitori', 'japanese', 'main', false, 40, 'Skewers of chicken thigh and leek grilled over charcoal and brushed with tare.', NOW(), NOW()),
    ('Matcha ice cream', 'japanese', 'dessert', true, 30, 'Creamy green tea ice cream with a slightly bitter grassy flavor.', NOW(), NOW()),
    ('Mochi', 'japanese', 'dessert', true, 40, 'Chewy rice cakes filled with sweet red bean paste.', NOW(), NOW()),
    ('Udon noodle soup', 'japanese', 'soup', true, 25, 'Thick chewy wheat noodles in a hot soy dashi broth with scallions and fried tofu.', NOW(), NOW()),
    ('Tamagoyaki', 'japanese', 'breakfast', true, 15, 'Rolled sweet omelette cooked in thin layers in a rectangular pan.', NOW(), NOW()),
    ('Sukiyaki', 'japanese', 'main', false, 40, 'Thin slices of beef, tofu and vegetables simmered at the table in a sweet soy broth.', NOW(), NOW()),
    ('Cucumber sunomono', 'japanese', 'side', true, 10, 'Refreshing salad of thin cucumber slices in rice vinegar with sesame seeds.', NOW(), NOW()),
    ('Takoyaki', 'japanese', 'starter', false, 40, 'Round batter balls filled with octopus, street food from Osaka.', NOW(), NOW()),
    -- chinese
    ('Kung pao chicken', 'chinese', 'main', false, 25, 'Stir fried chicken with peanuts, dried chilies and Sichuan pepper in a sweet and sour sauce.', NOW(), NOW()),
    ('Mapo tofu', 'chinese', 'main', false, 25, 'Silken tofu in a spicy and numbing Sichuan sauce of chili bean paste and minced pork.', NOW(), NOW()),
    ('Peking duck', 'chinese', 'main', false, 1440, 'Roast duck with crispy lacquered skin served in thin pancakes with hoisin sauce and cucumber.', NOW(), NOW()),
    ('Char siu pork', 'chinese', 'main', false, 120, 'Cantonese barbecued pork glazed with honey, five spice and hoisin.', NOW(), NOW()),
    ('Egg fried rice', 'chinese', 'side', true, 15, 'Day old rice stir fried in a hot wok with egg, peas and scallions.', NOW(), NOW()),
    ('Hot and sour soup', 'chinese', 'soup', false, 30, 'Thick soup with tofu, mushrooms, bamboo shoots and egg ribbons, sharp with vinegar and white pepper.', NOW(), NOW()),
    ('Wonton soup', 'chinese', 'soup', false, 45, 'Delicate pork and shrimp dumplings in a clear chicken broth.', NOW(), NOW()),
    ('Dan dan noodles', 'chinese', 'main', false, 25, 'Noodles with spicy chili oil, sesame paste, Sichuan pepper and crispy minced pork.', NOW(), NOW()),
    ('Sweet and sour pork', 'chinese', 'main', false, 40, 'Crispy fried pork with pineapple and peppers in a glossy sweet and sour sauce.', NOW(), NOW()),
    ('Dim sum har gow', 'chinese', 'starter', false, 60, 'Steamed shrimp dumplings with translucent wrappers.', NOW(), NOW()),
    ('Spring rolls', 'chinese', 'starter', true, 40, 'Crispy fried rolls filled with cabbage, carrots, mushrooms and glass noodles.', NOW(), NOW()),
    ('Stir fried bok choy', 'chinese', 'side', true, 10, 'Baby bok choy flash fried with garlic and a dash of oyster sauce.', NOW(), NOW()),
    ('Chow mein', 'chinese', 'main', false, 20, 'Stir fried egg noodles with chicken, bean sprouts, cabbage and soy sauce.', NOW(), NOW()),
    ('Beef and broccoli', 'chinese', 'main', false, 25, 'Tender beef slices and broccoli florets in a savory garlic and oyster sauce.', NOW(), NOW()),
    ('Scallion pancakes', 'chinese', 'starter', true, 45, 'Flaky pan fried flatbreads layered with green onions and sesame oil.', NOW(), NOW()),
    ('Steamed pork buns', 'chinese', 'starter', false, 120, 'Fluffy white buns filled with sweet barbecued pork.', NOW(), NOW()),
    ('Congee', 'chinese', 'breakfast', false, 90, 'Comforting rice porridge cooked for a long time, with ginger, scallions and century egg.', NOW(), NOW()),
    ('Egg tarts', 'chinese', 'dessert', true, 50, 'Flaky pastry shells with a smooth sweet egg custard, a Hong Kong bakery classic.', NOW(), NOW()),
    ('Tea eggs', 'chinese', 'side', true, 120, 'Boiled eggs with cracked shells simmered in tea, soy and star anise, marbled inside.', NOW(), NOW()),
    ('Ma po eggplant', 'chinese', 'main', true, 30, 'Silky eggplant braised in a garlicky spicy bean sauce.', NOW(), NOW()),
    -- indian
    ('Butter chicken', 'indian', 'main', false, 60, 'Tandoori chicken in a mild creamy tomato and butter sauce with fenugreek.', NOW(), NOW()),
    ('Chana masala', 'indian', 'main', true, 45, 'Chickpeas simmered in a spicy tomato and onion gravy with garam masala.', NOW(), NOW()),
    ('Palak paneer', 'indian', 'main', true, 40, 'Cubes of fresh paneer cheese in a smooth spiced spinach sauce.', NOW(), NOW()),
    ('Dal tadka', 'indian', 'main', true, 40, 'Yellow lentils tempered with cumin, garlic, dried chili and ghee, a warming everyday dish.', NOW(), NOW()),
    ('Lamb rogan josh', 'indian', 'main', false, 120, 'Kashmiri lamb curry slowly cooked with yogurt, Kashmiri chili and aromatic spices.', NOW(), NOW()),
    ('Chicken biryani', 'indian', 'main', false, 90, 'Layered basmati rice and spiced chicken cooked together with saffron, fried onions and mint.', NOW(), NOW()),
    ('Vegetable samosas', 'indian', 'starter', true, 60, 'Crispy fried pastry triangles stuffed with spiced potatoes and peas.', NOW(), NOW()),
    ('Onion bhaji', 'indian', 'starter', true, 30, 'Crunchy fritters of sliced onions in a spiced chickpea flour batter.', NOW(), NOW()),
    ('Garlic naan', 'indian', 'side', true, 120, 'Soft leavened flatbread baked in a hot oven and brushed with garlic butter.', NOW(), NOW()),
    ('Raita', 'indian', 'side', true, 10, 'Cooling yogurt with cucumber, mint and roasted cumin, served with spicy dishes.', NOW(), NOW()),
    ('Aloo gobi', 'indian', 'main', true, 35, 'Dry curry of potatoes and cauliflower with turmeric, cumin and ginger.', NOW(), NOW()),
    ('Masala dosa', 'indian', 'breakfast', true, 30, 'Thin crispy fermented rice and lentil crepe filled with spiced potatoes, served with chutney and sambar.', NOW(), NOW()),
    ('Mango lassi', 'indian', 'drink', true, 5, 'Sweet and creamy yogurt drink blended with ripe mango and a pinch of cardamom.', NOW(), NOW()),
    ('Masala chai', 'indian', 'drink', true, 10, 'Black tea simmered with milk, ginger, cardamom, cinnamon and cloves.', NOW(), NOW()),
    ('Gulab jamun', 'indian', 'dessert', true, 45, 'Soft fried milk dumplings soaked in a rose and cardamom sugar syrup.', NOW(), NOW()),
    ('Kheer', 'indian', 'dessert', true, 60, 'Creamy rice pudding cooked in milk with cardamom, saffron and pistachios.', NOW(), NOW()),
    ('Tandoori chicken', 'indian', 'main', false, 240, 'Chicken marinated in yogurt and spices, roasted very hot until charred.', NOW(), NOW()),
    ('Rasam', 'indian', 'soup', true, 30, 'Thin tangy South Indian soup of tamarind, tomato, black pepper and curry leaves.', NOW(), NOW()),
    ('Pav bhaji', 'indian', 'main', true, 45, 'Mumbai street food of mashed spiced vegetables cooked with butter and eaten with soft buns.', NOW(), NOW()),
    ('Fish curry', 'indian', 'main', false, 40, 'Goan fish curry with coconut milk, tamarind and red chilies.', NOW(), NOW()),
    -- mexican
    ('Tacos al pastor', 'mexican', 'main', false, 180, 'Corn tortillas with pork marinated in chili and achiote, grilled with pineapple.', NOW(), NOW()),
    ('Guacamole', 'mexican', 'starter', true, 10, 'Mashed avocado with lime, cilantro, onion, tomato and jalapeno, served with tortilla chips.', NOW(), NOW()),
    ('Chicken enchiladas', 'mexican', 'main', false, 60, 'Tortillas rolled around shredded chicken, covered with red chili sauce and cheese and baked.', NOW(), NOW()),
    ('Chiles rellenos', 'mexican', 'main', true, 60, 'Roasted poblano peppers stuffed with cheese, dipped in egg batter and fried, in tomato sauce.', NOW(), NOW()),
    ('Pozole rojo', 'mexican', 'soup', false, 180, 'Hearty hominy and pork stew in a red chili broth, topped with radish, cabbage and lime.', NOW(), NOW()),
    ('Black bean soup', 'mexican', 'soup', true, 50, 'Smoky black bean soup with cumin and chipotle, topped with sour cream and avocado.', NOW(), NOW()),
    ('Huevos rancheros', 'mexican', 'breakfast', true, 20, 'Fried eggs on tortillas with a warm tomato and chili salsa and refried beans.', NOW(), NOW()),
    ('Chilaquiles', 'mexican', 'breakfast', true, 25, 'Fried tortilla chips simmered in green salsa, topped with crema, cheese and a fried egg.', NOW(), NOW()),
    ('Carnitas', 'mexican', 'main', false, 210, 'Pork shoulder slowly confit in lard with orange and garlic, then crisped and shredded.', NOW(), NOW()),
    ('Mole poblano', 'mexican', 'main', false, 240, 'Turkey in a dark complex sauce of dried chilies, chocolate, nuts and spices.', NOW(), NOW()),
    ('Elote', 'mexican', 'side', true, 20, 'Grilled corn on the cob slathered with mayonnaise, cotija cheese, chili powder and lime.', NOW(), NOW()),
    ('Pico de gallo', 'mexican', 'side', true, 10, 'Fresh salsa of chopped tomato, onion, jalapeno, cilantro and lime.', NOW(), NOW()),
    ('Fish tacos', 'mexican', 'main', false, 30, 'Beer battered fried fish in tortillas with cabbage slaw and chipotle cream.', NOW(), NOW()),
    ('Quesadillas', 'mexican', 'main', true, 15, 'Tortillas folded around melted Oaxaca cheese and mushrooms, toasted in a pan.', NOW(), NOW()),
    ('Churros', 'mexican', 'dessert', true, 30, 'Fried dough sticks rolled in cinnamon sugar and dipped in thick hot chocolate.', NOW(), NOW()),
    ('Tres leches cake', 'mexican', 'dessert', true, 90, 'Sponge cake soaked in three kinds of milk and topped with whipped cream.', NOW(), NOW()),
    ('Horchata', 'mexican', 'drink', true, 15, 'Cold sweet rice milk drink flavored with cinnamon and vanilla.', NOW(), NOW()),
    ('Margarita', 'mexican', 'drink', true, 5, 'Cocktail of tequila, lime juice and orange liqueur served in a salt rimmed glass.', NOW(), NOW()),
    ('Ceviche', 'mexican', 'starter', false, 30, 'Raw white fish cured in lime juice with onion, chili, tomato and cilantro, light and refreshing.', NOW(), NOW()),
    ('Tamales', 'mexican', 'main', false, 180, 'Corn masa dough filled with pork in red chili, wrapped in corn husks and steamed.', NOW(), NOW()),
    -- thai
    ('Pad thai', 'thai', 'main', false, 30, 'Stir fried rice noodles with shrimp, egg, tofu, bean sprouts and peanuts in a tamarind sauce.', NOW(), NOW()),
    ('Green curry', 'thai', 'main', false, 35, 'Chicken and Thai eggplant in a spicy coconut milk curry with green chilies and basil.', NOW(), NOW()),
    ('Tom yum goong', 'thai', 'soup', false, 25, 'Hot and sour shrimp soup with lemongrass, galangal, kaffir lime leaves and chili.', NOW(), NOW()),
    ('Tom kha gai', 'thai', 'soup', false, 30, 'Creamy coconut chicken soup with galangal, lemongrass and lime.', NOW(), NOW()),
    ('Massaman curry', 'thai', 'main', false, 120, 'Mild rich curry of beef, potatoes and peanuts with cinnamon and cardamom.', NOW(), NOW()),
    ('Som tam', 'thai', 'starter', true, 15, 'Crunchy green papaya salad pounded with lime, chili, garlic, tomatoes and peanuts.', NOW(), NOW()),
    ('Pad kra pao', 'thai', 'main', false, 15, 'Minced pork stir fried with holy basil, garlic and chilies, served with rice and a fried egg.', NOW(), NOW()),
    ('Mango sticky rice', 'thai', 'dessert', true, 40, 'Sweet glutinous rice with coconut cream and slices of ripe mango.', NOW(), NOW()),
    ('Panang curry', 'thai', 'main', false, 30, 'Thick red curry of beef with coconut cream, peanuts and kaffir lime.', NOW(), NOW()),
    ('Larb', 'thai', 'starter', false, 20, 'Minced meat salad with lime, fish sauce, mint, shallots and toasted rice powder.', NOW(), NOW()),
    ('Thai fried rice', 'thai', 'main', false, 15, 'Jasmine rice fried with egg, crab, onion and fish sauce, served with lime and cucumber.', NOW(), NOW()),
    ('Satay skewers', 'thai', 'starter', false, 60, 'Grilled marinated chicken skewers with a sweet peanut sauce.', NOW(), NOW()),
    ('Red curry with tofu', 'thai', 'main', true, 30, 'Tofu, bamboo shoots and bell peppers in a spicy red coconut curry.', NOW(), NOW()),
    ('Pad see ew', 'thai', 'main', false, 20, 'Wide rice noodles stir fried with Chinese broccoli, egg and dark soy sauce.', NOW(), NOW()),
    ('Thai iced tea', 'thai', 'drink', true, 10, 'Strong spiced black tea sweetened with condensed milk and poured over ice.', NOW(), NOW()),
    ('Khao soi', 'thai', 'soup', false, 50, 'Northern Thai curry noodle soup with coconut milk, chicken and crispy fried noodles on top.', NOW(), NOW()),
    ('Fresh summer rolls', 'thai', 'starter', true, 25, 'Rice paper rolls with herbs, vermicelli and vegetables, served with a peanut dip.', NOW(), NOW()),
    ('Thai beef salad', 'thai', 'starter', false, 25, 'Grilled beef sliced over herbs, cucumber and tomato with a lime and chili dressing.', NOW(), NOW()),
    ('Coconut pudding', 'thai', 'dessert', true, 30, 'Small two layer coconut custards steamed in banana leaf cups.', NOW(), NOW()),
    ('Morning glory stir fry', 'thai', 'side', true, 10, 'Water spinach flash fried with garlic, chili and soybean paste.', NOW(), NOW()),
    -- spanish
    ('Paella valenciana', 'spanish', 'main', false, 75, 'Saffron rice cooked in a wide pan with chicken, rabbit, green beans and a crispy socarrat.', NOW(), NOW()),
    ('Seafood paella', 'spanish', 'main', false, 60, 'Saffron rice with shrimp, mussels, squid and clams cooked in fish stock.', NOW(), NOW()),
    ('Gazpacho', 'spanish', 'soup', true, 15, 'Cold blended soup of ripe tomatoes, cucumber, pepper, garlic and olive oil, for hot summer days.', NOW(), NOW()),
    ('Salmorejo', 'spanish', 'soup', true, 15, 'Thick cold tomato and bread soup from Cordoba topped with egg and ham.', NOW(), NOW()),
    ('Tortilla espanola', 'spanish', 'main', true, 45, 'Thick omelette of potatoes and onions slowly cooked in olive oil.', NOW(), NOW()),
    ('Patatas bravas', 'spanish', 'starter', true, 40, 'Crispy fried potatoes with a spicy tomato sauce and garlic aioli.', NOW(), NOW()),
    ('Gambas al ajillo', 'spanish', 'starter', false, 15, 'Shrimp sizzling in olive oil with plenty of garlic and dried chili.', NOW(), NOW()),
    ('Pan con tomate', 'spanish', 'starter', true, 10, 'Toasted bread rubbed with ripe tomato, garlic, olive oil and salt.', NOW(), NOW()),
    ('Croquetas de jamon', 'spanish', 'starter', false, 90, 'Creamy bechamel croquettes with serrano ham, breaded and fried.', NOW(), NOW()),
    ('Pulpo a la gallega', 'spanish', 'starter', false, 60, 'Tender boiled octopus on potatoes with olive oil, coarse salt and smoked paprika.', NOW(), NOW()),
    ('Fabada asturiana', 'spanish', 'main', false, 180, 'Rich stew of large white beans with chorizo, morcilla and pork belly.', NOW(), NOW()),
    ('Albondigas', 'spanish', 'main', false, 50, 'Pork and beef meatballs simmered in a tomato and saffron sauce.', NOW(), NOW()),
    ('Pimientos de padron', 'spanish', 'side', true, 10, 'Small green peppers blistered in olive oil and sprinkled with sea salt, some of them hot.', NOW(), NOW()),
    ('Crema catalana', 'spanish', 'dessert', true, 40, 'Custard flavored with lemon and cinnamon under a burnt sugar crust.', NOW(), NOW()),
    ('Churros con chocolate', 'spanish', 'breakfast', true, 30, 'Crisp fried dough with a cup of thick drinking chocolate for dipping.', NOW(), NOW()),
    ('Sangria', 'spanish', 'drink', true, 10, 'Red wine punch with oranges, apples, brandy and sparkling water, served cold.', NOW(), NOW()),
    ('Espinacas con garbanzos', 'spanish', 'main', true, 30, 'Spinach and chickpeas with cumin, smoked paprika and fried bread, from Seville.', NOW(), NOW()),
    ('Pisto manchego', 'spanish', 'main', true, 50, 'Stew of tomatoes, peppers, zucchini and onions, often topped with a fried egg.', NOW(), NOW()),
    ('Tarta de Santiago', 'spanish', 'dessert', true, 60, 'Moist almond cake from Galicia dusted with powdered sugar.', NOW(), NOW()),
    ('Calamares a la romana', 'spanish', 'starter', false, 20, 'Squid rings in a light batter, deep fried and served with lemon.', NOW(), NOW()),
    -- greek
    ('Moussaka', 'greek', 'main', false, 120, 'Baked layers of eggplant, spiced lamb mince and a thick bechamel topping.', NOW(), NOW()),
    ('Greek salad', 'greek', 'starter', true, 10, 'Tomatoes, cucumber, red onion, olives and a slab of feta with oregano and olive oil.', NOW(), NOW()),
    ('Spanakopita', 'greek', 'main', true, 75, 'Flaky filo pie filled with spinach, feta, dill and scallions.', NOW(), NOW()),
    ('Souvlaki', 'greek', 'main', false, 40, 'Grilled pork skewers marinated in lemon, garlic and oregano, served in pita with tzatziki.', NOW(), NOW()),
    ('Tzatziki', 'greek', 'side', true, 10, 'Thick yogurt dip with grated cucumber, garlic, dill and olive oil.', NOW(), NOW()),
    ('Avgolemono', 'greek', 'soup', false, 50, 'Chicken and rice soup thickened with eggs and lemon, silky and tangy.', NOW(), NOW()),
    ('Dolmades', 'greek', 'starter', true, 90, 'Vine leaves rolled around rice with herbs and lemon, served at room temperature.', NOW(), NOW()),
    ('Gemista', 'greek', 'main', true, 90, 'Tomatoes and peppers stuffed with herbed rice and baked with potatoes.', NOW(), NOW()),
    ('Pastitsio', 'greek', 'main', false, 120, 'Baked tubular pasta with cinnamon spiced meat sauce and creamy bechamel.', NOW(), NOW()),
    ('Fasolada', 'greek', 'soup', true, 120, 'White bean soup with tomatoes, carrots, celery and plenty of olive oil.', NOW(), NOW()),
    ('Grilled octopus', 'greek', 'starter', false, 90, 'Charred octopus tentacles with olive oil, lemon and oregano.', NOW(), NOW()),
    ('Kleftiko', 'greek', 'main', false, 240, 'Lamb slowly baked in parchment with garlic, lemon, potatoes and herbs.', NOW(), NOW()),
    ('Baklava', 'greek', 'dessert', true, 90, 'Layers of buttered filo and chopped walnuts soaked in honey syrup.', NOW(), NOW()),
    ('Loukoumades', 'greek', 'dessert', true, 60, 'Small fried dough balls drizzled with honey and cinnamon.', NOW(), NOW()),
    ('Galaktoboureko', 'greek', 'dessert', true, 90, 'Semolina custard baked in filo and soaked in lemon syrup.', NOW(), NOW()),
    ('Greek yogurt with honey', 'greek', 'breakfast', true, 5, 'Thick strained yogurt with thyme honey and toasted walnuts.', NOW(), NOW()),
    ('Saganaki', 'greek', 'starter', true, 10, 'Pan fried slab of cheese, crisp outside and melting inside, with lemon.', NOW(), NOW()),
    ('Briam', 'greek', 'main', true, 90, 'Roasted summer vegetables with potatoes, zucchini, tomatoes and olive oil.', NOW(), NOW()),
    ('Keftedes', 'greek', 'starter', false, 40, 'Fried meatballs flavored with mint, oregano and onion.', NOW(), NOW()),
    ('Horiatiki pita', 'greek', 'side', true, 60, 'Soft homemade pita flatbreads cooked in a dry pan.', NOW(), NOW()),
    -- lebanese
    ('Hummus', 'lebanese', 'starter', true, 20, 'Smooth chickpea dip with tahini, lemon, garlic and a pool of olive oil.', NOW(), NOW()),
    ('Baba ganoush', 'lebanese', 'starter', true, 45, 'Smoky dip of charred eggplant with tahini, lemon and garlic.', NOW(), NOW()),
    ('Tabbouleh', 'lebanese', 'starter', true, 20, 'Fresh salad of finely chopped parsley, mint, tomato and bulgur with lemon.', NOW(), NOW()),
    ('Fattoush', 'lebanese', 'starter', true, 20, 'Crunchy salad of vegetables and toasted pita with sumac and pomegranate molasses.', NOW(), NOW()),
    ('Falafel', 'lebanese', 'main', true, 40, 'Crispy fried balls of ground chickpeas and herbs, served in pita with tahini sauce.', NOW(), NOW()),
    ('Chicken shawarma', 'lebanese', 'main', false, 60, 'Spiced marinated chicken roasted and sliced, wrapped with garlic sauce and pickles.', NOW(), NOW()),
    ('Kibbeh', 'lebanese', 'starter', false, 90, 'Fried torpedoes of bulgur and minced lamb stuffed with spiced meat and pine nuts.', NOW(), NOW()),
    ('Mujadara', 'lebanese', 'main', true, 50, 'Lentils and rice cooked with cumin and topped with deeply caramelized onions.', NOW(), NOW()),
    ('Lentil soup', 'lebanese', 'soup', true, 40, 'Smooth red lentil soup with cumin and lemon, a warming bowl for winter.', NOW(), NOW()),
    ('Manakish zaatar', 'lebanese', 'breakfast', true, 60, 'Flatbread baked with a topping of zaatar thyme, sesame and olive oil.', NOW(), NOW()),
    ('Labneh', 'lebanese', 'starter', true, 1440, 'Strained thick yogurt cheese drizzled with olive oil and mint.', NOW(), NOW()),
    ('Kafta', 'lebanese', 'main', false, 30, 'Grilled skewers of minced lamb with parsley, onion and spices.', NOW(), NOW()),
    ('Fatteh', 'lebanese', 'main', true, 30, 'Layers of crisp pita, chickpeas and garlicky yogurt topped with pine nuts.', NOW(), NOW()),
    ('Muhammara', 'lebanese', 'starter', true, 20, 'Roasted red pepper and walnut dip with pomegranate molasses.', NOW(), NOW()),
    ('Stuffed zucchini', 'lebanese', 'main', false, 90, 'Zucchini stuffed with rice and minced meat, simmered in tomato sauce.', NOW(), NOW()),
    ('Knafeh', 'lebanese', 'dessert', true, 60, 'Warm sweet cheese pastry with shredded filo, soaked in orange blossom syrup.', NOW(), NOW()),
    ('Maamoul', 'lebanese', 'dessert', true, 90, 'Shortbread cookies filled with dates or pistachios.', NOW(), NOW()),
    ('Mint lemonade', 'lebanese', 'drink', true, 10, 'Blended lemon juice with fresh mint and ice, very refreshing in summer.', NOW(), NOW()),
    ('Ful medames', 'lebanese', 'breakfast', true, 20, 'Warm fava beans mashed with garlic, lemon, cumin and olive oil.', NOW(), NOW()),
    ('Sayadieh', 'lebanese', 'main', false, 70, 'Spiced fish with rice cooked in a dark caramelized onion broth.', NOW(), NOW()),
    -- moroccan
    ('Chicken tagine with preserved lemon', 'moroccan', 'main', false, 90, 'Chicken slowly cooked in a clay pot with preserved lemons, green olives, ginger and saffron.', NOW(), NOW()),
    ('Lamb tagine with prunes', 'moroccan', 'main', false, 150, 'Lamb braised with prunes, honey, cinnamon and toasted almonds, sweet and savory.', NOW(), NOW()),
    ('Vegetable couscous', 'moroccan', 'main', true, 75, 'Steamed couscous with a broth of carrots, turnips, zucchini, chickpeas and raisins.', NOW(), NOW()),
    ('Harira', 'moroccan', 'soup', false, 90, 'Hearty tomato soup with lentils, chickpeas, lamb and herbs, eaten to break the Ramadan fast.', NOW(), NOW()),
    ('Bastilla', 'moroccan', 'main', false, 150, 'Flaky pastry pie of pigeon or chicken, almonds and spices, dusted with sugar and cinnamon.', NOW(), NOW()),
    ('Zaalouk', 'moroccan', 'side', true, 40, 'Cooked salad of eggplant and tomato with garlic, cumin and paprika.', NOW(), NOW()),
    ('Moroccan carrot salad', 'moroccan', 'starter', true, 20, 'Cooked carrots with cumin, orange blossom water, lemon and parsley.', NOW(), NOW()),
    ('Kefta tagine', 'moroccan', 'main', false, 50, 'Spiced meatballs in tomato sauce with eggs poached on top.', NOW(), NOW()),
    ('Shakshuka', 'moroccan', 'breakfast', true, 30, 'Eggs poached in a spicy sauce of tomatoes and peppers, eaten with bread.', NOW(), NOW()),
    ('Msemen', 'moroccan', 'breakfast', true, 60, 'Square layered flatbreads cooked on a griddle, served with honey and butter.', NOW(), NOW()),
    ('Mint tea', 'moroccan', 'drink', true, 10, 'Green tea brewed with plenty of fresh mint and sugar, poured from high above.', NOW(), NOW()),
    ('Mechoui', 'moroccan', 'main', false, 300, 'Whole lamb shoulder slowly roasted with cumin and butter until meltingly tender.', NOW(), NOW()),
    ('Fish chermoula', 'moroccan', 'main', false, 45, 'White fish marinated in a herb, garlic and spice paste and baked with tomatoes.', NOW(), NOW()),
    ('Bissara', 'moroccan', 'soup', true, 60, 'Thick fava bean soup with cumin, paprika and olive oil, a winter breakfast.', NOW(), NOW()),
    ('Chebakia', 'moroccan', 'dessert', true, 120, 'Flower shaped sesame cookies fried and coated in honey.', NOW(), NOW()),
    ('Orange and cinnamon salad', 'moroccan', 'dessert', true, 10, 'Orange slices with orange blossom water, cinnamon and mint.', NOW(), NOW()),
    ('Briouats', 'moroccan', 'starter', false, 60, 'Small fried pastry triangles filled with spiced minced meat.', NOW(), NOW()),
    ('Seffa', 'moroccan', 'dessert', true, 60, 'Sweet steamed vermicelli with butter, cinnamon, sugar and almonds.', NOW(), NOW()),
    ('Taktouka', 'moroccan', 'side', true, 40, 'Cooked salad of roasted green peppers and tomatoes.', NOW(), NOW()),
    ('Rfissa', 'moroccan', 'main', false, 120, 'Chicken with lentils and fenugreek over shredded msemen bread.', NOW(), NOW()),
    -- american
    ('Classic cheeseburger', 'american', 'main', false, 25, 'Grilled beef patty with melted cheddar, pickles, onion, lettuce and tomato in a toasted bun.', NOW(), NOW()),
    ('Mac and cheese', 'american', 'main', true, 40, 'Elbow pasta baked in a creamy cheddar sauce under a crunchy breadcrumb crust, pure comfort food.', NOW(), NOW()),
    ('Buttermilk pancakes', 'american', 'breakfast', true, 25, 'Fluffy stacked pancakes served with butter and maple syrup.', NOW(), NOW()),
    ('Southern fried chicken', 'american', 'main', false, 60, 'Buttermilk marinated chicken in a seasoned crispy crust, fried until golden.', NOW(), NOW()),
    ('Barbecue pulled pork', 'american', 'main', false, 600, 'Pork shoulder smoked low and slow, shredded and tossed in tangy barbecue sauce.', NOW(), NOW()),
    ('Texas chili con carne', 'american', 'main', false, 180, 'Beef chili slowly simmered with dried chilies, cumin and garlic, warming in cold weather.', NOW(), NOW()),
    ('New England clam chowder', 'american', 'soup', false, 50, 'Creamy soup of clams, potatoes, onion and bacon.', NOW(), NOW()),
    ('Caesar salad', 'american', 'starter', false, 20, 'Romaine lettuce with a garlic and anchovy dressing, croutons and parmesan.', NOW(), NOW()),
    ('Buffalo wings', 'american', 'starter', false, 50, 'Fried chicken wings tossed in hot sauce and butter, served with blue cheese dip.', NOW(), NOW()),
    ('Cornbread', 'american', 'side', true, 35, 'Slightly sweet golden bread made with cornmeal and baked in a cast iron skillet.', NOW(), NOW()),
    ('Coleslaw', 'american', 'side', true, 15, 'Crunchy shredded cabbage and carrots in a creamy tangy dressing.', NOW(), NOW()),
    ('Apple pie', 'american', 'dessert', true, 120, 'Double crust pie filled with cinnamon spiced apples, served warm with vanilla ice cream.', NOW(), NOW()),
    ('New York cheesecake', 'american', 'dessert', true, 480, 'Dense and creamy baked cheesecake on a graham cracker crust.', NOW(), NOW()),
    ('Chocolate chip cookies', 'american', 'dessert', true, 30, 'Chewy cookies with crisp edges loaded with chocolate chips.', NOW(), NOW()),
    ('Brownies', 'american', 'dessert', true, 40, 'Fudgy dense chocolate squares with a crackly top.', NOW(), NOW()),
    ('Eggs Benedict', 'american', 'breakfast', false, 30, 'Poached eggs and ham on English muffins covered with hollandaise sauce.', NOW(), NOW()),
    ('Lobster roll', 'american', 'main', false, 40, 'Chunks of lobster with mayonnaise or butter in a toasted split top bun.', NOW(), NOW()),
    ('Gumbo', 'american', 'soup', false, 150, 'Louisiana stew of dark roux, okra, andouille sausage, chicken and shrimp.', NOW(), NOW()),
    ('Jambalaya', 'american', 'main', false, 60, 'Creole rice cooked with chicken, sausage, shrimp, peppers and spices.', NOW(), NOW()),
    ('Pumpkin pie', 'american', 'dessert', true, 90, 'Spiced pumpkin custard pie for Thanksgiving, with whipped cream.', NOW(), NOW()),
    -- korean
    ('Bibimbap', 'korean', 'main', false, 45, 'Rice bowl with seasoned vegetables, beef, a fried egg and spicy gochujang.', NOW(), NOW()),
    ('Kimchi jjigae', 'korean', 'soup', false, 35, 'Spicy bubbling stew of aged kimchi, pork belly and tofu, ideal on a cold day.', NOW(), NOW()),
    ('Bulgogi', 'korean', 'main', false, 40, 'Thin slices of beef marinated in soy, pear, garlic and sesame, grilled quickly.', NOW(), NOW()),
    ('Korean fried chicken', 'korean', 'main', false, 60, 'Twice fried extra crispy chicken glazed with a sweet and spicy gochujang sauce.', NOW(), NOW()),
    ('Japchae', 'korean', 'main', true, 40, 'Sweet potato glass noodles stir fried with vegetables, mushrooms and sesame oil.', NOW(), NOW()),
    ('Kimchi', 'korean', 'side', true, 2880, 'Napa cabbage fermented with chili, garlic, ginger and fish sauce.', NOW(), NOW()),
    ('Tteokbokki', 'korean', 'main', false, 25, 'Chewy rice cakes in a sweet and fiery red chili sauce with fish cakes.', NOW(), NOW()),
    ('Sundubu jjigae', 'korean', 'soup', false, 25, 'Soft tofu stew in a spicy broth with seafood and an egg cracked in at the end.', NOW(), NOW()),
    ('Samgyetang', 'korean', 'soup', false, 120, 'Whole young chicken stuffed with rice, ginseng and jujube in a clear restorative broth.', NOW(), NOW()),
    ('Kimchi pancake', 'korean', 'starter', true, 25, 'Crispy savory pancake with chopped kimchi and scallions.', NOW(), NOW()),
    ('Galbi', 'korean', 'main', false, 240, 'Beef short ribs marinated in soy and pear, grilled at the table.', NOW(), NOW()),
    ('Kimbap', 'korean', 'main', false, 45, 'Seaweed rice rolls filled with egg, spinach, carrot, pickled radish and beef.', NOW(), NOW()),
    ('Doenjang jjigae', 'korean', 'soup', true, 30, 'Earthy soybean paste stew with zucchini, tofu, potato and mushrooms.', NOW(), NOW()),
    ('Seasoned spinach', 'korean', 'side', true, 10, 'Blanched spinach dressed with sesame oil, garlic and toasted sesame seeds.', NOW(), NOW()),
    ('Hotteok', 'korean', 'dessert', true, 60, 'Pan fried sweet pancakes filled with brown sugar, cinnamon and nuts, winter street food.', NOW(), NOW()),
    ('Bingsu', 'korean', 'dessert', true, 15, 'Shaved milk ice topped with sweet red beans, fruit and condensed milk, a summer treat.', NOW(), NOW()),
    ('Dakgalbi', 'korean', 'main', false, 40, 'Spicy stir fried chicken with cabbage, sweet potato and rice cakes.', NOW(), NOW()),
    ('Naengmyeon', 'korean', 'main', false, 30, 'Chewy buckwheat noodles in an icy cold tangy beef broth, for hot weather.', NOW(), NOW()),
    ('Gyeran jjim', 'korean', 'side', false, 15, 'Fluffy steamed egg custard with scallions, served bubbling in a stone pot.', NOW(), NOW()),
    ('Sikhye', 'korean', 'drink', true, 300, 'Sweet cold rice punch with floating grains of rice.', NOW(), NOW()),
    -- vietnamese
    ('Pho bo', 'vietnamese', 'soup', false, 360, 'Fragrant beef broth with star anise and cinnamon, rice noodles, thin beef slices and fresh herbs.', NOW(), NOW()),
    ('Banh mi', 'vietnamese', 'main', false, 30, 'Crusty baguette with pork, pate, pickled carrots and daikon, cilantro and chili.', NOW(), NOW()),
    ('Bun cha', 'vietnamese', 'main', false, 60, 'Grilled pork patties in a sweet fish sauce broth with rice noodles and herbs.', NOW(), NOW()),
    ('Goi cuon', 'vietnamese', 'starter', false, 30, 'Fresh rice paper rolls with shrimp, pork, vermicelli and herbs, with hoisin peanut sauce.', NOW(), NOW()),
    ('Cha gio', 'vietnamese', 'starter', false, 60, 'Crispy fried spring rolls with pork, mushrooms and glass noodles.', NOW(), NOW()),
    ('Bun bo Hue', 'vietnamese', 'soup', false, 240, 'Spicy lemongrass beef noodle soup from Hue.', NOW(), NOW()),
    ('Com tam', 'vietnamese', 'main', false, 45, 'Broken rice with grilled pork chop, fried egg and fish sauce.', NOW(), NOW()),
    ('Ca kho to', 'vietnamese', 'main', false, 50, 'Catfish caramelized in a clay pot with fish sauce and black pepper.', NOW(), NOW()),
    ('Banh xeo', 'vietnamese', 'main', false, 40, 'Crispy turmeric rice crepe filled with shrimp, pork and bean sprouts.', NOW(), NOW()),
    ('Vegetarian pho', 'vietnamese', 'soup', true, 90, 'Aromatic vegetable broth with charred ginger and onion, rice noodles, tofu and herbs.', NOW(), NOW()),
    ('Lemongrass tofu', 'vietnamese', 'main', true, 25, 'Crispy tofu stir fried with lemongrass, chili and garlic.', NOW(), NOW()),
    ('Green papaya salad', 'vietnamese', 'starter', true, 20, 'Shredded green papaya with herbs, peanuts and a sweet lime dressing.', NOW(), NOW()),
    ('Ca phe sua da', 'vietnamese', 'drink', true, 10, 'Strong drip coffee with sweetened condensed milk over ice.', NOW(), NOW()),
    ('Che ba mau', 'vietnamese', 'dessert', true, 60, 'Three color dessert of beans, jelly and coconut milk over crushed ice.', NOW(), NOW()),
    ('Morning glory with garlic', 'vietnamese', 'side', true, 10, 'Water spinach stir fried with lots of garlic.', NOW(), NOW()),
    ('Canh chua', 'vietnamese', 'soup', false, 40, 'Sour tamarind soup with fish, pineapple, tomato and bean sprouts.', NOW(), NOW()),
    ('Bo luc lac', 'vietnamese', 'main', false, 30, 'Shaking beef, cubes of steak seared with garlic and served with watercress.', NOW(), NOW()),
    ('Xoi', 'vietnamese', 'breakfast', true, 60, 'Sticky rice with mung beans and fried shallots, a breakfast on the go.', NOW(), NOW()),
    ('Banh flan', 'vietnamese', 'dessert', true, 60, 'Caramel custard with a touch of coffee.', NOW(), NOW()),
    ('Chicken congee', 'vietnamese', 'breakfast', false, 75, 'Soothing chicken rice porridge with ginger, a remedy when you feel sick.', NOW(), NOW()),
    -- british
    ('Fish and chips', 'british', 'main', false, 45, 'Cod in crisp beer batter with thick cut fries, mushy peas and tartare sauce.', NOW(), NOW()),
    ('Shepherds pie', 'british', 'main', false, 90, 'Minced lamb in gravy topped with mashed potato and baked until golden, a winter comfort dish.', NOW(), NOW()),
    ('Full English breakfast', 'british', 'breakfast', false, 30, 'Fried eggs, bacon, sausages, baked beans, mushrooms, tomato and toast.', NOW(), NOW()),
    ('Beef Wellington', 'british', 'main', false, 150, 'Beef fillet coated with mushroom duxelles and wrapped in puff pastry, a festive roast.', NOW(), NOW()),
    ('Sunday roast beef', 'british', 'main', false, 180, 'Roast beef with Yorkshire puddings, roast potatoes, vegetables and gravy.', NOW(), NOW()),
    ('Bangers and mash', 'british', 'main', false, 40, 'Pork sausages with creamy mashed potatoes and onion gravy.', NOW(), NOW()),
    ('Cornish pasty', 'british', 'main', false, 90, 'Hand held pastry filled with beef, potato, swede and onion.', NOW(), NOW()),
    ('Welsh rarebit', 'british', 'starter', true, 15, 'Toast covered with a savory sauce of cheddar, mustard, ale and Worcestershire.', NOW(), NOW()),
    ('Leek and potato soup', 'british', 'soup', true, 40, 'Simple creamy soup of leeks and potatoes.', NOW(), NOW()),
    ('Scones with clotted cream', 'british', 'dessert', true, 30, 'Light scones served with clotted cream and strawberry jam for afternoon tea.', NOW(), NOW()),
    ('Sticky toffee pudding', 'british', 'dessert', true, 60, 'Moist date sponge drenched in a hot toffee sauce, served with custard.', NOW(), NOW()),
    ('Eton mess', 'british', 'dessert', true, 15, 'Crushed meringue, whipped cream and strawberries mixed together, a summer dessert.', NOW(), NOW()),
    ('Bread and butter pudding', 'british', 'dessert', true, 60, 'Buttered bread baked in custard with raisins and nutmeg.', NOW(), NOW()),
    ('Toad in the hole', 'british', 'main', false, 50, 'Sausages baked in a puffed Yorkshire pudding batter.', NOW(), NOW()),
    ('Chicken tikka masala', 'british', 'main', false, 60, 'Grilled chicken pieces in a creamy spiced tomato sauce, a British curry house favorite.', NOW(), NOW()),
    ('Steak and ale pie', 'british', 'main', false, 180, 'Beef braised in dark ale under a flaky pastry lid.', NOW(), NOW()),
    ('Kedgeree', 'british', 'breakfast', false, 40, 'Curried rice with smoked haddock, boiled eggs and parsley.', NOW(), NOW()),
    ('Ploughmans lunch', 'british', 'starter', true, 10, 'Cold plate of cheddar, crusty bread, pickle, apple and pickled onions.', NOW(), NOW()),
    ('Mushy peas', 'british', 'side', true, 20, 'Marrowfat peas cooked down into a thick green mash.', NOW(), NOW()),
    ('Mulled wine', 'british', 'drink', true, 20, 'Hot red wine with orange, cinnamon, cloves and star anise, for Christmas evenings.', NOW(), NOW()),
    -- ethiopian
    ('Doro wat', 'ethiopian', 'main', false, 150, 'Spicy chicken stew with berbere, slowly cooked onions and hard boiled eggs.', NOW(), NOW()),
    ('Misir wat', 'ethiopian', 'main', true, 50, 'Red lentils simmered in a spicy berbere sauce.', NOW(), NOW()),
    ('Injera', 'ethiopian', 'side', true, 4320, 'Spongy sour flatbread of fermented teff flour, used to scoop the stews.', NOW(), NOW()),
    ('Shiro', 'ethiopian', 'main', true, 30, 'Smooth chickpea flour stew with garlic, onion and berbere.', NOW(), NOW()),
    ('Gomen', 'ethiopian', 'side', true, 40, 'Collard greens slowly cooked with garlic, ginger and spiced butter.', NOW(), NOW()),
    ('Tibs', 'ethiopian', 'main', false, 25, 'Sauteed beef cubes with onions, rosemary, chili and spiced butter.', NOW(), NOW()),
    ('Kitfo', 'ethiopian', 'main', false, 15, 'Raw minced beef warmed in spiced butter and mitmita chili.', NOW(), NOW()),
    ('Atakilt wat', 'ethiopian', 'main', true, 45, 'Mild stew of cabbage, potatoes and carrots with turmeric.', NOW(), NOW()),
    ('Ethiopian coffee', 'ethiopian', 'drink', true, 30, 'Green coffee beans roasted on the spot, ground and brewed in a jebena pot.', NOW(), NOW()),
    ('Fasolia', 'ethiopian', 'side', true, 30, 'Green beans and carrots sauteed with garlic and onion.', NOW(), NOW()),
    ('Key wat', 'ethiopian', 'main', false, 120, 'Beef stew in a deep red berbere and onion sauce.', NOW(), NOW()),
    ('Azifa', 'ethiopian', 'starter', true, 40, 'Cold green lentil salad with lime, mustard, chili and onion.', NOW(), NOW()),
    ('Genfo', 'ethiopian', 'breakfast', true, 20, 'Thick barley porridge with a well of spiced butter and chili.', NOW(), NOW()),
    ('Dabo kolo', 'ethiopian', 'side', true, 40, 'Small crunchy spiced bread snacks.', NOW(), NOW()),
    ('Tikil gomen', 'ethiopian', 'side', true, 40, 'Cabbage, carrots and potatoes cooked with turmeric and ginger.', NOW(), NOW()),
    ('Asa tibs', 'ethiopian', 'main', false, 30, 'Fried fish with onions, peppers and garlic.', NOW(), NOW()),
    ('Ful', 'ethiopian', 'breakfast', true, 20, 'Spiced fava beans with tomato, egg, yogurt and bread.', NOW(), NOW()),
    ('Tej', 'ethiopian', 'drink', true, 20160, 'Traditional honey wine fermented with gesho leaves.', NOW(), NOW()),
    ('Kik alicha', 'ethiopian', 'main', true, 50, 'Mild yellow split pea stew with turmeric, garlic and ginger.', NOW(), NOW()),
    ('Ayib', 'ethiopian', 'side', true, 60, 'Fresh crumbly cottage cheese to cool down the spicy dishes.', NOW(), NOW()),
    -- nordic
    ('Swedish meatballs', 'nordic', 'main', false, 45, 'Small pork and beef meatballs in a creamy gravy with lingonberry jam and mashed potatoes.', NOW(), NOW()),
    ('Gravlax', 'nordic', 'starter', false, 2880, 'Salmon cured with salt, sugar and dill, served with a mustard dill sauce.', NOW(), NOW()),
    ('Smorrebrod', 'nordic', 'starter', false, 20, 'Danish open sandwiches on rye bread with herring, egg, shrimp or roast beef.', NOW(), NOW()),
    ('Cinnamon buns', 'nordic', 'dessert', true, 150, 'Soft cardamom scented yeast buns rolled with cinnamon butter, for coffee breaks.', NOW(), NOW()),
    ('Salmon soup', 'nordic', 'soup', false, 40, 'Finnish creamy salmon and potato soup with dill and leeks.', NOW(), NOW()),
    ('Pickled herring', 'nordic', 'starter', false, 1440, 'Herring fillets marinated in sweet vinegar with onions and allspice.', NOW(), NOW()),
    ('Janssons temptation', 'nordic', 'side', false, 75, 'Gratin of potato matchsticks, onions, sprats and cream, a Christmas classic.', NOW(), NOW()),
    ('Rye bread', 'nordic', 'side', true, 1440, 'Dense dark sourdough rye bread full of seeds.', NOW(), NOW()),
    ('Pea soup with pork', 'nordic', 'soup', false, 150, 'Thick yellow pea soup with salt pork, eaten on Thursdays with pancakes.', NOW(), NOW()),
    ('Mushroom and barley stew', 'nordic', 'main', true, 60, 'Earthy stew of wild mushrooms, pearl barley and thyme for autumn evenings.', NOW(), NOW()),
    ('Kanelbulle porridge', 'nordic', 'breakfast', true, 15, 'Oat porridge with cinnamon, cardamom, apple and a spoon of butter.', NOW(), NOW()),
    ('Skagenrora', 'nordic', 'starter', false, 20, 'Shrimp salad with mayonnaise, dill and lemon on toast, topped with roe.', NOW(), NOW()),
    ('Karelian pies', 'nordic', 'side', true, 90, 'Thin rye crusts filled with rice porridge, topped with egg butter.', NOW(), NOW()),
    ('Princess cake', 'nordic', 'dessert', true, 180, 'Sponge cake with jam, custard and a dome of whipped cream covered in green marzipan.', NOW(), NOW()),
    ('Glogg', 'nordic', 'drink', true, 30, 'Hot spiced wine with almonds and raisins, served in winter.', NOW(), NOW()),
    ('Roasted root vegetables', 'nordic', 'side', true, 50, 'Beetroot, carrots, parsnips and celeriac roasted with thyme and honey.', NOW(), NOW()),
    ('Reindeer stew', 'nordic', 'main', false, 60, 'Thin slices of reindeer sauteed with butter and cream, served with mashed potatoes and lingonberries.', NOW(), NOW()),
    ('Blueberry pie', 'nordic', 'dessert', true, 60, 'Crumbly pie of wild blueberries, served with vanilla sauce.', NOW(), NOW()),
    ('Fish cakes', 'nordic', 'main', false, 40, 'Norwegian fish cakes of cod and cream, pan fried and served with potatoes.', NOW(), NOW()),
    ('Cucumber salad with dill', 'nordic', 'side', true, 10, 'Thin cucumber slices in a sweet vinegar dressing with dill.', NOW(), NOW());
