//                         -----
//                     -------------
//                   -----  ----------
//                  ---  --------------
//                 ---  ----------------
//                 --- -----------------
//                 --- -----------------
//                 --- -----------------
//                 ---------------------
//       -----      -------------------       -----
//      -------      --  ---------- --      -------
//          ----      ---------------      -----
//           ---      ---------------      ----
//          ----     -----------------     ----
//        ------   ----------------------   ------
//    --------  ---------------------------  --------
//   ------   -------------------------- ----   -------
//  ----    -----  ---------- --- ------- -----    -----
// ----  ------  -------- --- --- ---- ---  ------  ----
// ----        ---- ----  --- ---- ---- -----       ----
//  ----   ------  ----  ---- ----  ----   ------  -----
//  ------      ------   ---- -----  ------      ------
//    ---------------    ----  ----    --------------
//      ----------       ----  ----      ----------
//                       ----  ----
//                 ---   ---- -----   --
//               ------  ---- ----- -------
//              -------  ---- ----- --------
//              ----    ----   -----    ----
//              -----------     -----------
//               ---------        --------
//
// Don't touch this file.
// It is automatically generated by the octopux crate cli.

#![recursion_limit = "1024"]
mod helpers;
mod models {
    pub mod account;
    pub mod accountrole;
    pub mod address;
    pub mod apikey;
    pub mod attachment;
    pub mod attribute;
    pub mod attributevalue;
    pub mod auditlog;
    pub mod brand;
    pub mod budget;
    pub mod campaign;
    pub mod campaignchannel;
    pub mod carrier;
    pub mod cart;
    pub mod cartitem;
    pub mod category;
    pub mod city;
    pub mod company;
    pub mod contract;
    pub mod country;
    pub mod coupon;
    pub mod creditnote;
    pub mod currency;
    pub mod customer;
    pub mod customeraddress;
    pub mod customersegment;
    pub mod customersegmentmember;
    pub mod department;
    pub mod employee;
    pub mod employeeskill;
    pub mod expense;
    pub mod fiscalyear;
    pub mod goodsreceipt;
    pub mod invoice;
    pub mod invoiceline;
    pub mod jobtitle;
    pub mod journal;
    pub mod journalentry;
    pub mod journalline;
    pub mod language;
    pub mod lead;
    pub mod leaverequest;
    pub mod leavetype;
    pub mod ledgeraccount;
    pub mod milestone;
    pub mod notification;
    pub mod opportunity;
    pub mod ordercoupon;
    pub mod payment;
    pub mod paymentmethod;
    pub mod payslip;
    pub mod permission;
    pub mod pricelist;
    pub mod pricelistitem;
    pub mod product;
    pub mod productimage;
    pub mod producttag;
    pub mod productvariant;
    pub mod project;
    pub mod purchaseorder;
    pub mod purchaseorderline;
    pub mod quote;
    pub mod quoteline;
    pub mod refund;
    pub mod region;
    pub mod returnitem;
    pub mod returnrequest;
    pub mod review;
    pub mod role;
    pub mod rolepermission;
    pub mod salesorder;
    pub mod salesorderline;
    pub mod session;
    pub mod shipment;
    pub mod shipmentitem;
    pub mod skill;
    pub mod sla;
    pub mod stocklevel;
    pub mod stockmovement;
    pub mod storagelocation;
    pub mod supplier;
    pub mod suppliercontact;
    pub mod tag;
    pub mod task;
    pub mod taskattachment;
    pub mod taskcomment;
    pub mod taxrate;
    pub mod team;
    pub mod teammember;
    pub mod ticket;
    pub mod ticketmessage;
    pub mod ticketsla;
    pub mod timeentry;
    pub mod timezone;
    pub mod variantattribute;
    pub mod warehouse;
    pub mod webhook;
    pub mod webhookdelivery;
    pub mod wishlist;
    pub mod wishlistitem;
    pub mod account_accountroles;
    pub mod account_apikeys;
    pub mod account_attachments;
    pub mod account_auditlogs;
    pub mod account_employees;
    pub mod account_notifications;
    pub mod account_roles;
    pub mod account_sessions;
    pub mod account_taskcomments;
    pub mod account_ticketmessages;
    pub mod address_customeraddresses;
    pub mod address_salesorders;
    pub mod address_salesorders_by_shipping_address;
    pub mod address_warehouses;
    pub mod attachment_taskattachments;
    pub mod attachment_tasks;
    pub mod attribute_attributevalues;
    pub mod attributevalue_productvariants;
    pub mod attributevalue_variantattributes;
    pub mod brand_products;
    pub mod budget_expenses;
    pub mod campaign_campaignchannels;
    pub mod campaign_leads;
    pub mod carrier_shipments;
    pub mod cart_cartitems;
    pub mod category_categories;
    pub mod category_products;
    pub mod city_addresses;
    pub mod company_customers;
    pub mod company_departments;
    pub mod company_fiscalyears;
    pub mod company_projects;
    pub mod country_companies;
    pub mod country_regions;
    pub mod country_suppliers;
    pub mod country_taxrates;
    pub mod coupon_ordercoupons;
    pub mod coupon_salesorders;
    pub mod currency_companies;
    pub mod currency_pricelists;
    pub mod currency_salesorders;
    pub mod customer_carts;
    pub mod customer_customeraddresses;
    pub mod customer_customersegmentmembers;
    pub mod customer_customersegments;
    pub mod customer_invoices;
    pub mod customer_opportunities;
    pub mod customer_projects;
    pub mod customer_reviews;
    pub mod customer_salesorders;
    pub mod customer_tickets;
    pub mod customer_wishlists;
    pub mod customersegment_customers;
    pub mod customersegment_customersegmentmembers;
    pub mod department_budgets;
    pub mod department_departments;
    pub mod department_employees;
    pub mod department_teams;
    pub mod employee_contracts;
    pub mod employee_employees;
    pub mod employee_employeeskills;
    pub mod employee_expenses;
    pub mod employee_leads;
    pub mod employee_leaverequests;
    pub mod employee_payslips;
    pub mod employee_tasks;
    pub mod employee_teammembers;
    pub mod employee_teams;
    pub mod employee_teams_by_employee;
    pub mod employee_tickets;
    pub mod employee_timeentries;
    pub mod fiscalyear_budgets;
    pub mod invoice_creditnotes;
    pub mod invoice_invoicelines;
    pub mod invoice_payments;
    pub mod jobtitle_employees;
    pub mod journal_journalentries;
    pub mod journalentry_journallines;
    pub mod language_accounts;
    pub mod lead_opportunities;
    pub mod leavetype_leaverequests;
    pub mod ledgeraccount_journallines;
    pub mod ledgeraccount_ledgeraccounts;
    pub mod milestone_tasks;
    pub mod opportunity_quotes;
    pub mod payment_refunds;
    pub mod paymentmethod_payments;
    pub mod permission_rolepermissions;
    pub mod permission_roles;
    pub mod pricelist_pricelistitems;
    pub mod product_productimages;
    pub mod product_producttags;
    pub mod product_productvariants;
    pub mod product_reviews;
    pub mod product_tags;
    pub mod productvariant_attributevalues;
    pub mod productvariant_cartitems;
    pub mod productvariant_pricelistitems;
    pub mod productvariant_purchaseorderlines;
    pub mod productvariant_quotelines;
    pub mod productvariant_salesorderlines;
    pub mod productvariant_stocklevels;
    pub mod productvariant_stockmovements;
    pub mod productvariant_variantattributes;
    pub mod productvariant_wishlistitems;
    pub mod productvariant_wishlists;
    pub mod project_milestones;
    pub mod project_tasks;
    pub mod purchaseorder_goodsreceipts;
    pub mod purchaseorder_purchaseorderlines;
    pub mod quote_quotelines;
    pub mod region_cities;
    pub mod returnrequest_returnitems;
    pub mod role_accountroles;
    pub mod role_accounts;
    pub mod role_permissions;
    pub mod role_rolepermissions;
    pub mod salesorder_coupons;
    pub mod salesorder_invoices;
    pub mod salesorder_ordercoupons;
    pub mod salesorder_returnrequests;
    pub mod salesorder_salesorderlines;
    pub mod salesorder_shipments;
    pub mod salesorderline_returnitems;
    pub mod salesorderline_shipmentitems;
    pub mod shipment_shipmentitems;
    pub mod skill_employeeskills;
    pub mod sla_tickets;
    pub mod sla_ticketslas;
    pub mod storagelocation_stocklevels;
    pub mod supplier_purchaseorders;
    pub mod supplier_suppliercontacts;
    pub mod tag_products;
    pub mod tag_producttags;
    pub mod task_attachments;
    pub mod task_taskattachments;
    pub mod task_taskcomments;
    pub mod task_timeentries;
    pub mod taxrate_salesorderlines;
    pub mod team_employees;
    pub mod team_teammembers;
    pub mod ticket_slas;
    pub mod ticket_ticketmessages;
    pub mod ticket_ticketslas;
    pub mod timezone_accounts;
    pub mod warehouse_purchaseorders;
    pub mod warehouse_shipments;
    pub mod warehouse_stockmovements;
    pub mod warehouse_stockmovements_by_to_warehouse;
    pub mod warehouse_storagelocations;
    pub mod webhook_webhookdeliveries;
    pub mod wishlist_productvariants;
    pub mod wishlist_wishlistitems;
}
use models::*;
use async_graphql::http::GraphiQLSource;
use async_graphql::{EmptySubscription, MergedObject, Object, Schema};
use async_graphql_actix_web::GraphQL;
use actix_web::web;
use apistos::app::{BuildConfig, OpenApiWrapper};
use apistos::info::Info;
use apistos::spec::Spec;
use apistos::SwaggerUIConfig;
use sqlx::PgPool;
use helpers::AppState;


async fn graphiql() -> actix_web::HttpResponse {
    actix_web::HttpResponse::Ok()
        .content_type("text/html; charset=utf-8")
        .body(GraphiQLSource::build().endpoint("/graphql").finish())
}

#[derive(Default)]
struct ApiQuery;

#[Object]
impl ApiQuery {
    async fn api_version(&self) -> &'static str {
        env!("CARGO_PKG_VERSION")
    }
}

// The GraphQL queries, merge the query roots of the models generated with --graphql here:
// `struct Query(ApiQuery, <model_name>::<Model>Query, ...);`
#[derive(MergedObject, Default)]
struct Query0(ApiQuery, account::AccountQuery, accountrole::AccountroleQuery, address::AddressQuery, apikey::ApikeyQuery, attachment::AttachmentQuery, attribute::AttributeQuery, attributevalue::AttributevalueQuery, auditlog::AuditlogQuery, brand::BrandQuery);
#[derive(MergedObject, Default)]
struct Query1(budget::BudgetQuery, campaign::CampaignQuery, campaignchannel::CampaignchannelQuery, carrier::CarrierQuery, cart::CartQuery, cartitem::CartitemQuery, category::CategoryQuery, city::CityQuery, company::CompanyQuery, contract::ContractQuery);
#[derive(MergedObject, Default)]
struct Query2(country::CountryQuery, coupon::CouponQuery, creditnote::CreditnoteQuery, currency::CurrencyQuery, customer::CustomerQuery, customeraddress::CustomeraddressQuery, customersegment::CustomersegmentQuery, customersegmentmember::CustomersegmentmemberQuery, department::DepartmentQuery, employee::EmployeeQuery);
#[derive(MergedObject, Default)]
struct Query3(employeeskill::EmployeeskillQuery, expense::ExpenseQuery, fiscalyear::FiscalyearQuery, goodsreceipt::GoodsreceiptQuery, invoice::InvoiceQuery, invoiceline::InvoicelineQuery, jobtitle::JobtitleQuery, journal::JournalQuery, journalentry::JournalentryQuery, journalline::JournallineQuery);
#[derive(MergedObject, Default)]
struct Query4(language::LanguageQuery, lead::LeadQuery, leaverequest::LeaverequestQuery, leavetype::LeavetypeQuery, ledgeraccount::LedgeraccountQuery, milestone::MilestoneQuery, notification::NotificationQuery, opportunity::OpportunityQuery, ordercoupon::OrdercouponQuery, payment::PaymentQuery);
#[derive(MergedObject, Default)]
struct Query5(paymentmethod::PaymentmethodQuery, payslip::PayslipQuery, permission::PermissionQuery, pricelist::PricelistQuery, pricelistitem::PricelistitemQuery, product::ProductQuery, productimage::ProductimageQuery, producttag::ProducttagQuery, productvariant::ProductvariantQuery, project::ProjectQuery);
#[derive(MergedObject, Default)]
struct Query6(purchaseorder::PurchaseorderQuery, purchaseorderline::PurchaseorderlineQuery, quote::QuoteQuery, quoteline::QuotelineQuery, refund::RefundQuery, region::RegionQuery, returnitem::ReturnitemQuery, returnrequest::ReturnrequestQuery, review::ReviewQuery, role::RoleQuery);
#[derive(MergedObject, Default)]
struct Query7(rolepermission::RolepermissionQuery, salesorder::SalesorderQuery, salesorderline::SalesorderlineQuery, session::SessionQuery, shipment::ShipmentQuery, shipmentitem::ShipmentitemQuery, skill::SkillQuery, sla::SlaQuery, stocklevel::StocklevelQuery, stockmovement::StockmovementQuery);
#[derive(MergedObject, Default)]
struct Query8(storagelocation::StoragelocationQuery, supplier::SupplierQuery, suppliercontact::SuppliercontactQuery, tag::TagQuery, task::TaskQuery, taskattachment::TaskattachmentQuery, taskcomment::TaskcommentQuery, taxrate::TaxrateQuery, team::TeamQuery, teammember::TeammemberQuery);
#[derive(MergedObject, Default)]
struct Query9(ticket::TicketQuery, ticketmessage::TicketmessageQuery, ticketsla::TicketslaQuery, timeentry::TimeentryQuery, timezone::TimezoneQuery, variantattribute::VariantattributeQuery, warehouse::WarehouseQuery, webhook::WebhookQuery, webhookdelivery::WebhookdeliveryQuery, wishlist::WishlistQuery);
#[derive(MergedObject, Default)]
struct Query10(wishlistitem::WishlistitemQuery);
#[derive(MergedObject, Default)]
struct Query(Query0, Query1, Query2, Query3, Query4, Query5, Query6, Query7, Query8, Query9, Query10, account::AccountQuery, accountrole::AccountroleQuery, address::AddressQuery, apikey::ApikeyQuery, attachment::AttachmentQuery, attribute::AttributeQuery, attributevalue::AttributevalueQuery, auditlog::AuditlogQuery, brand::BrandQuery, budget::BudgetQuery, campaign::CampaignQuery, campaignchannel::CampaignchannelQuery, carrier::CarrierQuery, cart::CartQuery, cartitem::CartitemQuery, category::CategoryQuery, city::CityQuery, company::CompanyQuery, contract::ContractQuery, country::CountryQuery, coupon::CouponQuery, creditnote::CreditnoteQuery, currency::CurrencyQuery, customer::CustomerQuery, customeraddress::CustomeraddressQuery, customersegment::CustomersegmentQuery, customersegmentmember::CustomersegmentmemberQuery, department::DepartmentQuery, employee::EmployeeQuery, employeeskill::EmployeeskillQuery, expense::ExpenseQuery, fiscalyear::FiscalyearQuery, goodsreceipt::GoodsreceiptQuery, invoice::InvoiceQuery, invoiceline::InvoicelineQuery, jobtitle::JobtitleQuery, journal::JournalQuery, journalentry::JournalentryQuery, journalline::JournallineQuery, language::LanguageQuery, lead::LeadQuery, leaverequest::LeaverequestQuery, leavetype::LeavetypeQuery, ledgeraccount::LedgeraccountQuery, milestone::MilestoneQuery, notification::NotificationQuery, opportunity::OpportunityQuery, ordercoupon::OrdercouponQuery, payment::PaymentQuery, paymentmethod::PaymentmethodQuery, payslip::PayslipQuery, permission::PermissionQuery, pricelist::PricelistQuery, pricelistitem::PricelistitemQuery, product::ProductQuery, productimage::ProductimageQuery, producttag::ProducttagQuery, productvariant::ProductvariantQuery, project::ProjectQuery, purchaseorder::PurchaseorderQuery, purchaseorderline::PurchaseorderlineQuery, quote::QuoteQuery, quoteline::QuotelineQuery, refund::RefundQuery, region::RegionQuery, returnitem::ReturnitemQuery, returnrequest::ReturnrequestQuery, review::ReviewQuery, role::RoleQuery, rolepermission::RolepermissionQuery, salesorder::SalesorderQuery, salesorderline::SalesorderlineQuery, session::SessionQuery, shipment::ShipmentQuery, shipmentitem::ShipmentitemQuery, skill::SkillQuery, sla::SlaQuery, stocklevel::StocklevelQuery, stockmovement::StockmovementQuery, storagelocation::StoragelocationQuery, supplier::SupplierQuery, suppliercontact::SuppliercontactQuery, tag::TagQuery, task::TaskQuery, taskattachment::TaskattachmentQuery, taskcomment::TaskcommentQuery, taxrate::TaxrateQuery, team::TeamQuery, teammember::TeammemberQuery, ticket::TicketQuery, ticketmessage::TicketmessageQuery, ticketsla::TicketslaQuery, timeentry::TimeentryQuery, timezone::TimezoneQuery, variantattribute::VariantattributeQuery, warehouse::WarehouseQuery, webhook::WebhookQuery, webhookdelivery::WebhookdeliveryQuery, wishlist::WishlistQuery, wishlistitem::WishlistitemQuery);

// The GraphQL mutations, GraphQL refusing a mutation root without fields, replace it once a model is generated with --graphql:
// `#[derive(MergedObject, Default)] struct Mutation(<model_name>::<Model>Mutation, ...);`
#[derive(MergedObject, Default)]
struct Mutation0(account::AccountMutation, accountrole::AccountroleMutation, address::AddressMutation, apikey::ApikeyMutation, attachment::AttachmentMutation, attribute::AttributeMutation, attributevalue::AttributevalueMutation, auditlog::AuditlogMutation, brand::BrandMutation, budget::BudgetMutation);
#[derive(MergedObject, Default)]
struct Mutation1(campaign::CampaignMutation, campaignchannel::CampaignchannelMutation, carrier::CarrierMutation, cart::CartMutation, cartitem::CartitemMutation, category::CategoryMutation, city::CityMutation, company::CompanyMutation, contract::ContractMutation, country::CountryMutation);
#[derive(MergedObject, Default)]
struct Mutation2(coupon::CouponMutation, creditnote::CreditnoteMutation, currency::CurrencyMutation, customer::CustomerMutation, customeraddress::CustomeraddressMutation, customersegment::CustomersegmentMutation, customersegmentmember::CustomersegmentmemberMutation, department::DepartmentMutation, employee::EmployeeMutation, employeeskill::EmployeeskillMutation);
#[derive(MergedObject, Default)]
struct Mutation3(expense::ExpenseMutation, fiscalyear::FiscalyearMutation, goodsreceipt::GoodsreceiptMutation, invoice::InvoiceMutation, invoiceline::InvoicelineMutation, jobtitle::JobtitleMutation, journal::JournalMutation, journalentry::JournalentryMutation, journalline::JournallineMutation, language::LanguageMutation);
#[derive(MergedObject, Default)]
struct Mutation4(lead::LeadMutation, leaverequest::LeaverequestMutation, leavetype::LeavetypeMutation, ledgeraccount::LedgeraccountMutation, milestone::MilestoneMutation, notification::NotificationMutation, opportunity::OpportunityMutation, ordercoupon::OrdercouponMutation, payment::PaymentMutation, paymentmethod::PaymentmethodMutation);
#[derive(MergedObject, Default)]
struct Mutation5(payslip::PayslipMutation, permission::PermissionMutation, pricelist::PricelistMutation, pricelistitem::PricelistitemMutation, product::ProductMutation, productimage::ProductimageMutation, producttag::ProducttagMutation, productvariant::ProductvariantMutation, project::ProjectMutation, purchaseorder::PurchaseorderMutation);
#[derive(MergedObject, Default)]
struct Mutation6(purchaseorderline::PurchaseorderlineMutation, quote::QuoteMutation, quoteline::QuotelineMutation, refund::RefundMutation, region::RegionMutation, returnitem::ReturnitemMutation, returnrequest::ReturnrequestMutation, review::ReviewMutation, role::RoleMutation, rolepermission::RolepermissionMutation);
#[derive(MergedObject, Default)]
struct Mutation7(salesorder::SalesorderMutation, salesorderline::SalesorderlineMutation, session::SessionMutation, shipment::ShipmentMutation, shipmentitem::ShipmentitemMutation, skill::SkillMutation, sla::SlaMutation, stocklevel::StocklevelMutation, stockmovement::StockmovementMutation, storagelocation::StoragelocationMutation);
#[derive(MergedObject, Default)]
struct Mutation8(supplier::SupplierMutation, suppliercontact::SuppliercontactMutation, tag::TagMutation, task::TaskMutation, taskattachment::TaskattachmentMutation, taskcomment::TaskcommentMutation, taxrate::TaxrateMutation, team::TeamMutation, teammember::TeammemberMutation, ticket::TicketMutation);
#[derive(MergedObject, Default)]
struct Mutation9(ticketmessage::TicketmessageMutation, ticketsla::TicketslaMutation, timeentry::TimeentryMutation, timezone::TimezoneMutation, variantattribute::VariantattributeMutation, warehouse::WarehouseMutation, webhook::WebhookMutation, webhookdelivery::WebhookdeliveryMutation, wishlist::WishlistMutation, wishlistitem::WishlistitemMutation);
#[derive(MergedObject, Default)]
struct Mutation(Mutation0, Mutation1, Mutation2, Mutation3, Mutation4, Mutation5, Mutation6, Mutation7, Mutation8, Mutation9, account::AccountMutation, accountrole::AccountroleMutation, address::AddressMutation, apikey::ApikeyMutation, attachment::AttachmentMutation, attribute::AttributeMutation, attributevalue::AttributevalueMutation, auditlog::AuditlogMutation, brand::BrandMutation, budget::BudgetMutation, campaign::CampaignMutation, campaignchannel::CampaignchannelMutation, carrier::CarrierMutation, cart::CartMutation, cartitem::CartitemMutation, category::CategoryMutation, city::CityMutation, company::CompanyMutation, contract::ContractMutation, country::CountryMutation, coupon::CouponMutation, creditnote::CreditnoteMutation, currency::CurrencyMutation, customer::CustomerMutation, customeraddress::CustomeraddressMutation, customersegment::CustomersegmentMutation, customersegmentmember::CustomersegmentmemberMutation, department::DepartmentMutation, employee::EmployeeMutation, employeeskill::EmployeeskillMutation, expense::ExpenseMutation, fiscalyear::FiscalyearMutation, goodsreceipt::GoodsreceiptMutation, invoice::InvoiceMutation, invoiceline::InvoicelineMutation, jobtitle::JobtitleMutation, journal::JournalMutation, journalentry::JournalentryMutation, journalline::JournallineMutation, language::LanguageMutation, lead::LeadMutation, leaverequest::LeaverequestMutation, leavetype::LeavetypeMutation, ledgeraccount::LedgeraccountMutation, milestone::MilestoneMutation, notification::NotificationMutation, opportunity::OpportunityMutation, ordercoupon::OrdercouponMutation, payment::PaymentMutation, paymentmethod::PaymentmethodMutation, payslip::PayslipMutation, permission::PermissionMutation, pricelist::PricelistMutation, pricelistitem::PricelistitemMutation, product::ProductMutation, productimage::ProductimageMutation, producttag::ProducttagMutation, productvariant::ProductvariantMutation, project::ProjectMutation, purchaseorder::PurchaseorderMutation, purchaseorderline::PurchaseorderlineMutation, quote::QuoteMutation, quoteline::QuotelineMutation, refund::RefundMutation, region::RegionMutation, returnitem::ReturnitemMutation, returnrequest::ReturnrequestMutation, review::ReviewMutation, role::RoleMutation, rolepermission::RolepermissionMutation, salesorder::SalesorderMutation, salesorderline::SalesorderlineMutation, session::SessionMutation, shipment::ShipmentMutation, shipmentitem::ShipmentitemMutation, skill::SkillMutation, sla::SlaMutation, stocklevel::StocklevelMutation, stockmovement::StockmovementMutation, storagelocation::StoragelocationMutation, supplier::SupplierMutation, suppliercontact::SuppliercontactMutation, tag::TagMutation, task::TaskMutation, taskattachment::TaskattachmentMutation, taskcomment::TaskcommentMutation, taxrate::TaxrateMutation, team::TeamMutation, teammember::TeammemberMutation, ticket::TicketMutation, ticketmessage::TicketmessageMutation, ticketsla::TicketslaMutation, timeentry::TimeentryMutation, timezone::TimezoneMutation, variantattribute::VariantattributeMutation, warehouse::WarehouseMutation, webhook::WebhookMutation, webhookdelivery::WebhookdeliveryMutation, wishlist::WishlistMutation, wishlistitem::WishlistitemMutation);

#[actix_web::main]
async fn main() -> std::io::Result<()> {
    let pool = PgPool::connect(&std::env::var("DATABASE_URL").expect("DATABASE_URL must be set")).await.unwrap();
    sqlx::migrate!().run(&pool).await.unwrap();
    let state = web::Data::new(AppState { pool });
    let schema = Schema::build(Query::default(), Mutation::default(), EmptySubscription)
        .data(state.clone())
        .finish();

    actix_web::HttpServer::new(move || {
        let spec = Spec {
            info: Info {
                title: "MyApp REST API".to_string(),
                version: "1.0.0".to_string(),
                ..Default::default()
            },
            ..Default::default()
        };
        actix_web::App::new()
            .document(spec)
            // Actix does not fall through between scopes sharing a prefix,
            .service(
            // so resources living under the same scope must be registered together
                apistos::web::scope("v1") // Where the magic operates
                    // Mount your models here with `.configure(<model_name>::configure)`
                    // after declaring them with `mod <model_name>;`
                    .configure(account::configure)
                    .configure(accountrole::configure)
                    .configure(address::configure)
                    .configure(apikey::configure)
                    .configure(attachment::configure)
                    .configure(attribute::configure)
                    .configure(attributevalue::configure)
                    .configure(auditlog::configure)
                    .configure(brand::configure)
                    .configure(budget::configure)
                    .configure(campaign::configure)
                    .configure(campaignchannel::configure)
                    .configure(carrier::configure)
                    .configure(cart::configure)
                    .configure(cartitem::configure)
                    .configure(category::configure)
                    .configure(city::configure)
                    .configure(company::configure)
                    .configure(contract::configure)
                    .configure(country::configure)
                    .configure(coupon::configure)
                    .configure(creditnote::configure)
                    .configure(currency::configure)
                    .configure(customer::configure)
                    .configure(customeraddress::configure)
                    .configure(customersegment::configure)
                    .configure(customersegmentmember::configure)
                    .configure(department::configure)
                    .configure(employee::configure)
                    .configure(employeeskill::configure)
                    .configure(expense::configure)
                    .configure(fiscalyear::configure)
                    .configure(goodsreceipt::configure)
                    .configure(invoice::configure)
                    .configure(invoiceline::configure)
                    .configure(jobtitle::configure)
                    .configure(journal::configure)
                    .configure(journalentry::configure)
                    .configure(journalline::configure)
                    .configure(language::configure)
                    .configure(lead::configure)
                    .configure(leaverequest::configure)
                    .configure(leavetype::configure)
                    .configure(ledgeraccount::configure)
                    .configure(milestone::configure)
                    .configure(notification::configure)
                    .configure(opportunity::configure)
                    .configure(ordercoupon::configure)
                    .configure(payment::configure)
                    .configure(paymentmethod::configure)
                    .configure(payslip::configure)
                    .configure(permission::configure)
                    .configure(pricelist::configure)
                    .configure(pricelistitem::configure)
                    .configure(product::configure)
                    .configure(productimage::configure)
                    .configure(producttag::configure)
                    .configure(productvariant::configure)
                    .configure(project::configure)
                    .configure(purchaseorder::configure)
                    .configure(purchaseorderline::configure)
                    .configure(quote::configure)
                    .configure(quoteline::configure)
                    .configure(refund::configure)
                    .configure(region::configure)
                    .configure(returnitem::configure)
                    .configure(returnrequest::configure)
                    .configure(review::configure)
                    .configure(role::configure)
                    .configure(rolepermission::configure)
                    .configure(salesorder::configure)
                    .configure(salesorderline::configure)
                    .configure(session::configure)
                    .configure(shipment::configure)
                    .configure(shipmentitem::configure)
                    .configure(skill::configure)
                    .configure(sla::configure)
                    .configure(stocklevel::configure)
                    .configure(stockmovement::configure)
                    .configure(storagelocation::configure)
                    .configure(supplier::configure)
                    .configure(suppliercontact::configure)
                    .configure(tag::configure)
                    .configure(task::configure)
                    .configure(taskattachment::configure)
                    .configure(taskcomment::configure)
                    .configure(taxrate::configure)
                    .configure(team::configure)
                    .configure(teammember::configure)
                    .configure(ticket::configure)
                    .configure(ticketmessage::configure)
                    .configure(ticketsla::configure)
                    .configure(timeentry::configure)
                    .configure(timezone::configure)
                    .configure(variantattribute::configure)
                    .configure(warehouse::configure)
                    .configure(webhook::configure)
                    .configure(webhookdelivery::configure)
                    .configure(wishlist::configure)
                    .configure(wishlistitem::configure)
                    .configure(account_accountroles::configure)
                    .configure(account_apikeys::configure)
                    .configure(account_attachments::configure)
                    .configure(account_auditlogs::configure)
                    .configure(account_employees::configure)
                    .configure(account_notifications::configure)
                    .configure(account_roles::configure)
                    .configure(account_sessions::configure)
                    .configure(account_taskcomments::configure)
                    .configure(account_ticketmessages::configure)
                    .configure(address_customeraddresses::configure)
                    .configure(address_salesorders::configure)
                    .configure(address_salesorders_by_shipping_address::configure)
                    .configure(address_warehouses::configure)
                    .configure(attachment_taskattachments::configure)
                    .configure(attachment_tasks::configure)
                    .configure(attribute_attributevalues::configure)
                    .configure(attributevalue_productvariants::configure)
                    .configure(attributevalue_variantattributes::configure)
                    .configure(brand_products::configure)
                    .configure(budget_expenses::configure)
                    .configure(campaign_campaignchannels::configure)
                    .configure(campaign_leads::configure)
                    .configure(carrier_shipments::configure)
                    .configure(cart_cartitems::configure)
                    .configure(category_categories::configure)
                    .configure(category_products::configure)
                    .configure(city_addresses::configure)
                    .configure(company_customers::configure)
                    .configure(company_departments::configure)
                    .configure(company_fiscalyears::configure)
                    .configure(company_projects::configure)
                    .configure(country_companies::configure)
                    .configure(country_regions::configure)
                    .configure(country_suppliers::configure)
                    .configure(country_taxrates::configure)
                    .configure(coupon_ordercoupons::configure)
                    .configure(coupon_salesorders::configure)
                    .configure(currency_companies::configure)
                    .configure(currency_pricelists::configure)
                    .configure(currency_salesorders::configure)
                    .configure(customer_carts::configure)
                    .configure(customer_customeraddresses::configure)
                    .configure(customer_customersegmentmembers::configure)
                    .configure(customer_customersegments::configure)
                    .configure(customer_invoices::configure)
                    .configure(customer_opportunities::configure)
                    .configure(customer_projects::configure)
                    .configure(customer_reviews::configure)
                    .configure(customer_salesorders::configure)
                    .configure(customer_tickets::configure)
                    .configure(customer_wishlists::configure)
                    .configure(customersegment_customers::configure)
                    .configure(customersegment_customersegmentmembers::configure)
                    .configure(department_budgets::configure)
                    .configure(department_departments::configure)
                    .configure(department_employees::configure)
                    .configure(department_teams::configure)
                    .configure(employee_contracts::configure)
                    .configure(employee_employees::configure)
                    .configure(employee_employeeskills::configure)
                    .configure(employee_expenses::configure)
                    .configure(employee_leads::configure)
                    .configure(employee_leaverequests::configure)
                    .configure(employee_payslips::configure)
                    .configure(employee_tasks::configure)
                    .configure(employee_teammembers::configure)
                    .configure(employee_teams::configure)
                    .configure(employee_teams_by_employee::configure)
                    .configure(employee_tickets::configure)
                    .configure(employee_timeentries::configure)
                    .configure(fiscalyear_budgets::configure)
                    .configure(invoice_creditnotes::configure)
                    .configure(invoice_invoicelines::configure)
                    .configure(invoice_payments::configure)
                    .configure(jobtitle_employees::configure)
                    .configure(journal_journalentries::configure)
                    .configure(journalentry_journallines::configure)
                    .configure(language_accounts::configure)
                    .configure(lead_opportunities::configure)
                    .configure(leavetype_leaverequests::configure)
                    .configure(ledgeraccount_journallines::configure)
                    .configure(ledgeraccount_ledgeraccounts::configure)
                    .configure(milestone_tasks::configure)
                    .configure(opportunity_quotes::configure)
                    .configure(payment_refunds::configure)
                    .configure(paymentmethod_payments::configure)
                    .configure(permission_rolepermissions::configure)
                    .configure(permission_roles::configure)
                    .configure(pricelist_pricelistitems::configure)
                    .configure(product_productimages::configure)
                    .configure(product_producttags::configure)
                    .configure(product_productvariants::configure)
                    .configure(product_reviews::configure)
                    .configure(product_tags::configure)
                    .configure(productvariant_attributevalues::configure)
                    .configure(productvariant_cartitems::configure)
                    .configure(productvariant_pricelistitems::configure)
                    .configure(productvariant_purchaseorderlines::configure)
                    .configure(productvariant_quotelines::configure)
                    .configure(productvariant_salesorderlines::configure)
                    .configure(productvariant_stocklevels::configure)
                    .configure(productvariant_stockmovements::configure)
                    .configure(productvariant_variantattributes::configure)
                    .configure(productvariant_wishlistitems::configure)
                    .configure(productvariant_wishlists::configure)
                    .configure(project_milestones::configure)
                    .configure(project_tasks::configure)
                    .configure(purchaseorder_goodsreceipts::configure)
                    .configure(purchaseorder_purchaseorderlines::configure)
                    .configure(quote_quotelines::configure)
                    .configure(region_cities::configure)
                    .configure(returnrequest_returnitems::configure)
                    .configure(role_accountroles::configure)
                    .configure(role_accounts::configure)
                    .configure(role_permissions::configure)
                    .configure(role_rolepermissions::configure)
                    .configure(salesorder_coupons::configure)
                    .configure(salesorder_invoices::configure)
                    .configure(salesorder_ordercoupons::configure)
                    .configure(salesorder_returnrequests::configure)
                    .configure(salesorder_salesorderlines::configure)
                    .configure(salesorder_shipments::configure)
                    .configure(salesorderline_returnitems::configure)
                    .configure(salesorderline_shipmentitems::configure)
                    .configure(shipment_shipmentitems::configure)
                    .configure(skill_employeeskills::configure)
                    .configure(sla_tickets::configure)
                    .configure(sla_ticketslas::configure)
                    .configure(storagelocation_stocklevels::configure)
                    .configure(supplier_purchaseorders::configure)
                    .configure(supplier_suppliercontacts::configure)
                    .configure(tag_products::configure)
                    .configure(tag_producttags::configure)
                    .configure(task_attachments::configure)
                    .configure(task_taskattachments::configure)
                    .configure(task_taskcomments::configure)
                    .configure(task_timeentries::configure)
                    .configure(taxrate_salesorderlines::configure)
                    .configure(team_employees::configure)
                    .configure(team_teammembers::configure)
                    .configure(ticket_slas::configure)
                    .configure(ticket_ticketmessages::configure)
                    .configure(ticket_ticketslas::configure)
                    .configure(timezone_accounts::configure)
                    .configure(warehouse_purchaseorders::configure)
                    .configure(warehouse_shipments::configure)
                    .configure(warehouse_stockmovements::configure)
                    .configure(warehouse_stockmovements_by_to_warehouse::configure)
                    .configure(warehouse_storagelocations::configure)
                    .configure(webhook_webhookdeliveries::configure)
                    .configure(wishlist_productvariants::configure)
                    .configure(wishlist_wishlistitems::configure),
            )
            .app_data(state.clone())
            .build_with(
                "/openapi.json",
                BuildConfig::default().with(SwaggerUIConfig::new(&"/swagger")),
            )
            .service(
                web::resource("/graphql")
                    .route(web::post().to(GraphQL::new(schema.clone())))
                    .route(web::get().to(graphiql)),
            )
    })
    .bind(("127.0.0.1", 8085))?
    .run()
    .await
}
