--                         -----
--                     -------------
--                   -----  ----------
--                  ---  --------------
--                 ---  ----------------
--                 --- -----------------
--                 --- -----------------
--                 --- -----------------
--                 ---------------------
--       -----      -------------------       -----
--      -------      --  ---------- --      -------
--          ----      ---------------      -----
--           ---      ---------------      ----
--          ----     -----------------     ----
--        ------   ----------------------   ------
--    --------  ---------------------------  --------
--   ------   -------------------------- ----   -------
--  ----    -----  ---------- --- ------- -----    -----
-- ----  ------  -------- --- --- ---- ---  ------  ----
-- ----        ---- ----  --- ---- ---- -----       ----
--  ----   ------  ----  ---- ----  ----   ------  -----
--  ------      ------   ---- -----  ------      ------
--    ---------------    ----  ----    --------------
--      ----------       ----  ----      ----------
--                       ----  ----
--                 ---   ---- -----   --
--               ------  ---- ----- -------
--              -------  ---- ----- --------
--              ----    ----   -----    ----
--              -----------     -----------
--               ---------        --------
--
-- Don't touch this file.
-- It is automatically generated by the octopux crate cli.

CREATE TABLE IF NOT EXISTS salesorder (
    id BIGSERIAL PRIMARY KEY,
    reference VARCHAR(255) NOT NULL,
    customer_id INT8 NOT NULL,
    billing_address_id INT8 NOT NULL,
    shipping_address_id INT8 NOT NULL,
    currency_id INT8 NOT NULL,
    status VARCHAR(255) NOT NULL,
    total FLOAT8 NOT NULL,
    UNIQUE (reference),
    FOREIGN KEY (customer_id) REFERENCES customer (id),
    FOREIGN KEY (billing_address_id) REFERENCES address (id),
    FOREIGN KEY (shipping_address_id) REFERENCES address (id),
    FOREIGN KEY (currency_id) REFERENCES currency (id)
);
