--                         -----
--                     -------------
--                   -----  ----------
--                  ---  --------------
--                 ---  ----------------
--                 --- -----------------
--                 --- -----------------
--                 --- -----------------
--                 ---------------------
--       -----      -------------------       -----
--      -------      --  ---------- --      -------
--          ----      ---------------      -----
--           ---      ---------------      ----
--          ----     -----------------     ----
--        ------   ----------------------   ------
--    --------  ---------------------------  --------
--   ------   -------------------------- ----   -------
--  ----    -----  ---------- --- ------- -----    -----
-- ----  ------  -------- --- --- ---- ---  ------  ----
-- ----        ---- ----  --- ---- ---- -----       ----
--  ----   ------  ----  ---- ----  ----   ------  -----
--  ------      ------   ---- -----  ------      ------
--    ---------------    ----  ----    --------------
--      ----------       ----  ----      ----------
--                       ----  ----
--                 ---   ---- -----   --
--               ------  ---- ----- -------
--              -------  ---- ----- --------
--              ----    ----   -----    ----
--              -----------     -----------
--               ---------        --------
--
-- Don't touch this file.
-- It is automatically generated by the octopux crate cli.

CREATE TABLE IF NOT EXISTS employee (
    id BIGSERIAL PRIMARY KEY,
    matricule VARCHAR(255) NOT NULL,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    account_id INT8 NOT NULL,
    department_id INT8 NOT NULL,
    job_title_id INT8 NOT NULL,
    manager_id INT8,
    UNIQUE (matricule),
    FOREIGN KEY (account_id) REFERENCES account (id),
    FOREIGN KEY (department_id) REFERENCES department (id),
    FOREIGN KEY (job_title_id) REFERENCES jobtitle (id),
    FOREIGN KEY (manager_id) REFERENCES employee (id)
);
